export { default as Home } from "./home/Home";
export { default as Main } from "./main/Main";
export { default as Item } from "./item/Item";
export { default as Items } from "./items/Items";
export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Spinner } from "./spinner/Spinner";
export { default as Product } from "./product/Product";
export { default as Sidebar } from "./sidebar/Sidebar";
export { default as Getproduct } from "./getinfo/Getproduct";
export {default as EditProduct} from './editproduct/EditProduct';
export {default as DeleteProduct} from './deleteproduct/DeleteProduct';
export { default as SelectSearch } from "./select-search/SelectSearch";
