export { default as Home } from "./home/Home";
export { default as Item } from "./item/Item";
export { default as Header } from "./header/Header";
export { default as Typist } from './typist/Typist';
export { default as Footer } from "./footer/Footer";
export { default as Confirm} from "./confirm/Confirm";
export { default as Spinner } from "./spinner/Spinner";
export { default as Product } from "./product/Product";
export { default as Sidebar } from "./sidebar/Sidebar";
export { default as Getproduct } from "./getinfo/Getproduct";
export {default as EditProduct} from './editproduct/EditProduct';
export {default as DeleteProduct} from './deleteproduct/DeleteProduct';
