export { default as Home } from "./home/Home";
export { default as Item } from "./item/Item";
export { default as Users } from "./users/Users";
export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Confirm } from "./confirm/Confirm";
export { default as Spinner } from "./spinner/Spinner";
export { default as Product } from "./product/Product";
export { default as Sidebar } from "./sidebar/Sidebar";
export { default as Manager } from "./user/manager/Manager";
export { default as Getproduct } from "./getinfo/Getproduct";
export { default as EditUser} from './user/edit-user/EditUser';
export {default as ShowUser} from './user/show-user/ShowUser';
export { default as Register } from "./user/register/Register";
export { default as InsertProduct} from "./main/InsertProduct";
export { default as ImageUpload } from "./image-upload/ImageUpload";
export { default as EditProduct } from "./editproduct/EditProduct";
export { default as DeleteUser}  from "./user/delete-user/DeleteUser";
export { default as AvatarUpload } from "./avatar-upload/AvatarUpload";
export { default as ProfileUpload } from "./profile-upload/ProfileUpload";
export { default as ImageUploadSvg } from "./image-upload/ImageUploadSvg";
export { default as DeleteProduct } from "./deleteproduct/DeleteProduct";
export { default as NewAvatarUpload } from './new-avatar-upload/NewAvatarUpload';
export { default as InfiniteLoadingProducts} from "./main/InfiniteLoadingProducts";
export { default as InfiniteLoadingManager } from "./user/manager/InfiniteLoadingManager";
export { default as InfinitLoading } from "./infinit-loading-component/InfinitLoading";
export { default as UseInfiniteLoading } from "./use-infinite-loading/UseInfiniteLoading";
export { default as TestInfinitLoading } from "./test-infinit-loading/TestInfinitLoading";